services:
  postgres:
    image: postgres:15-alpine
    container_name: evoting-postgres
    environment:
      POSTGRES_DB: evoting_wabisabi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - evoting-network

  redis:
    image: redis:7-alpine
    container_name: evoting-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - evoting-network

  api-gateway:
    build: ./server1
    container_name: evoting-gateway
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=${NODE_ENV}
      - JWT_SECRET=${JWT_SECRET}
      - AUTH_SERVICE_URL=http://auth-service:3002
      - VOTE_SERVICE_URL=http://vote-service:3003
    depends_on:
      - postgres
      - redis
      - auth-service
      - vote-service
    networks:
      - evoting-network

  auth-service:
    build: ./server2
    container_name: evoting-auth
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - JWT_SECRET=${JWT_SECRET}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - postgres
      - redis
    networks:
      - evoting-network

  vote-service:
    build: ./server3
    container_name: evoting-vote
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=postgres
      - REDIS_HOST=redis
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - postgres
      - redis
    networks:
      - evoting-network

  admin-dashboard:
    build: ./admin
    container_name: evoting-admin
    ports:
      - "3006:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:3001
      - REACT_APP_WS_URL=http://localhost:3001
    depends_on:
      - api-gateway
    networks:
      - evoting-network

volumes:
  postgres_data:

networks:
  evoting-network:
    driver: bridge